name: Build TrollStore IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: List repository files
        run: |
          pwd
          ls -la
          find . -name "*.xcodeproj" -maxdepth 1

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Create entitlements file
        run: |
          cat > iSponsorBlockTV/TrollStore.entitlements << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>platform-application</key>
              <true/>
              <key>com.apple.private.security.no-container</key>
              <true/>
              <key>com.apple.security.app-sandbox</key>
              <false/>
              <key>com.apple.security.get-task-allow</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Prepare project for iOS
        run: |
          cat > iSponsorBlockTV/Info.plist.ios << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleDevelopmentRegion</key>
              <string>$(DEVELOPMENT_LANGUAGE)</string>
              <key>CFBundleExecutable</key>
              <string>$(EXECUTABLE_NAME)</string>
              <key>CFBundleIdentifier</key>
              <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
              <key>CFBundleInfoDictionaryVersion</key>
              <string>6.0</string>
              <key>CFBundleName</key>
              <string>$(PRODUCT_NAME)</string>
              <key>CFBundlePackageType</key>
              <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
              <key>CFBundleShortVersionString</key>
              <string>$(MARKETING_VERSION)</string>
              <key>CFBundleVersion</key>
              <string>$(CURRENT_PROJECT_VERSION)</string>
              <key>LSMinimumSystemVersion</key>
              <string>$(MACOSX_DEPLOYMENT_TARGET)</string>
              <key>UIDeviceFamily</key>
              <array>
                  <integer>1</integer>
                  <integer>2</integer>
              </array>
              <key>MinimumOSVersion</key>
              <string>14.0</string>
              <key>UIRequiresFullScreen</key>
              <true/>
          </dict>
          </plist>
          EOF
          
          cp iSponsorBlockTV/Info.plist.ios iSponsorBlockTV/Info.plist
          
      - name: Show project schemes
        run: |
          # Find project file
          PROJECT_FILE=$(find . -name "*.xcodeproj" -maxdepth 1 | head -1)
          echo "Found project file: $PROJECT_FILE"
          
          # List schemes
          xcodebuild -project "$PROJECT_FILE" -list
          
      - name: Build Archive
        run: |
          # Find project file
          PROJECT_FILE=$(find . -name "*.xcodeproj" -maxdepth 1 | head -1)
          echo "Using project file: $PROJECT_FILE"
          
          mkdir -p build
          
          # Get scheme name if available
          SCHEME_NAME=$(xcodebuild -project "$PROJECT_FILE" -list | grep -A 10 "Schemes:" | grep -v "Schemes:" | head -1 | xargs)
          
          if [ -z "$SCHEME_NAME" ]; then
            echo "Could not determine scheme name, using default 'iSponsorBlockTV'"
            SCHEME_NAME="iSponsorBlockTV"
          fi
          
          echo "Using scheme name: $SCHEME_NAME"
          
          xcodebuild clean archive \
            -project "$PROJECT_FILE" \
            -scheme "$SCHEME_NAME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/iSponsorBlockTV.xcarchive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            ENTITLEMENTS_REQUIRED=YES \
            EXPANDED_CODE_SIGN_IDENTITY="" \
            SWIFT_OPTIMIZATION_LEVEL="-O" \
            OTHER_CODE_SIGN_FLAGS="--entitlements iSponsorBlockTV/TrollStore.entitlements"
            
      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -r build/iSponsorBlockTV.xcarchive/Products/Applications/*.app Payload/
          zip -r iSponsorBlockTV-TrollStore.ipa Payload

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: trollstore-ipa
          name: TrollStore IPA
          draft: false
          prerelease: false
          files: iSponsorBlockTV-TrollStore.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
