name: Build IPA for TrollStore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install dependencies
        run: |
          sudo gem install xcpretty
          
      - name: Build Archive
        run: |
          xcodebuild clean archive \
            -project iSponsorBlock.xcodeproj \
            -scheme iSponsorBlockTV \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/iSponsorBlockTV.xcarchive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            ENTITLEMENTS_REQUIRED=YES \
            EXPANDED_CODE_SIGN_IDENTITY="" \
            STRIP_SWIFT_SYMBOLS=NO \
            COPY_PHASE_STRIP=NO \
            SWIFT_OPTIMIZATION_LEVEL="-O" | xcpretty

      - name: Create IPA Structure
        run: |
          mkdir -p Payload
          cp -r build/iSponsorBlockTV.xcarchive/Products/Applications/iSponsorBlockTV.app Payload/
          
      - name: Create IPA File
        run: |
          zip -r iSponsorBlockTV.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: iSponsorBlockTV
          path: iSponsorBlockTV.ipa
          retention-days: 7